[package]
name = "arrow-parquet-list-test"
version = "0.1.0"
authors = ["melkor"]
edition = "2018"

[dependencies]
arrow = { git = "https://github.com/apache/arrow-rs.git" }
parquet = { git = "https://github.com/apache/arrow-rs.git" }
parquet-format = "4.0"
